// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service contains the business logic and provides methods exposed to the frontend
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as arcov1$0 from "../../api/v1/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as backup_profile$0 from "../backup_profile/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as statemachine$0 from "../statemachine/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../types/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$1 from "../../borg/types/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as ent$0 from "../../ent/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AbortBackup immediately aborts a running backup operation
 */
export function AbortBackup(backupId: types$0.BackupId): $CancellablePromise<void> {
    return $Call.ByID(1933267942, backupId);
}

/**
 * AbortBackups aborts multiple running backup operations
 */
export function AbortBackups(backupIds: types$0.BackupId[]): $CancellablePromise<void> {
    return $Call.ByID(4217672591, backupIds);
}

/**
 * All retrieves all repositories
 */
export function All(): $CancellablePromise<($models.Repository | null)[]> {
    return $Call.ByID(593256237).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * BreakLock breaks a repository lock
 */
export function BreakLock(repoId: number): $CancellablePromise<void> {
    return $Call.ByID(4281482770, repoId);
}

/**
 * CancelOperation cancels a queued or running operation
 */
export function CancelOperation(repositoryId: number, operationId: string): $CancellablePromise<void> {
    return $Call.ByID(3062607757, repositoryId, operationId);
}

/**
 * ChangePassphrase changes the passphrase of a repository's encryption key
 */
export function ChangePassphrase(repoId: number, currentPassword: string, newPassword: string): $CancellablePromise<$models.ChangePassphraseResult> {
    return $Call.ByID(4221631574, repoId, currentPassword, newPassword).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * Create creates a new repository
 */
export function Create(name: string, location: string, password: string, noPassword: boolean): $CancellablePromise<$models.Repository | null> {
    return $Call.ByID(3296679418, name, location, password, noPassword).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * CreateCloudRepository creates a new ArcoCloud repository
 */
export function CreateCloudRepository(name: string, password: string, location: arcov1$0.RepositoryLocation): $CancellablePromise<$models.Repository | null> {
    return $Call.ByID(2968644739, name, password, location).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Delete deletes a repository completely. This cancels all other operations
 */
export function Delete(id: number): $CancellablePromise<void> {
    return $Call.ByID(1592048265, id);
}

/**
 * ExaminePrunes analyzes what would be pruned with given rules
 */
export function ExaminePrunes(backupProfileId: number, pruningRule: backup_profile$0.PruningRule | null, saveResults: boolean): $CancellablePromise<$models.ExaminePruningResult[]> {
    return $Call.ByID(166629156, backupProfileId, pruningRule, saveResults).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * FixStoredPassword validates and updates the stored password for a repository
 */
export function FixStoredPassword(repoId: number, password: string): $CancellablePromise<$models.FixStoredPasswordResult> {
    return $Call.ByID(2845614759, repoId, password).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * Get retrieves a repository by ID
 */
export function Get(repoId: number): $CancellablePromise<$models.Repository | null> {
    return $Call.ByID(2350435594, repoId).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetActiveOperation(repoId: number, operationType: statemachine$0.OperationType | null): $CancellablePromise<$models.SerializableQueuedOperation | null> {
    return $Call.ByID(3370809829, repoId, operationType).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * GetBackupButtonStatus gets backup button status for given backup IDs
 */
export function GetBackupButtonStatus(backupIds: types$0.BackupId[]): $CancellablePromise<$models.BackupButtonStatus> {
    return $Call.ByID(1281128506, backupIds);
}

/**
 * GetBackupProfilesThatHaveOnlyRepo gets backup profiles that only have this repo
 */
export function GetBackupProfilesThatHaveOnlyRepo(repoId: number): $CancellablePromise<(ent$0.BackupProfile | null)[]> {
    return $Call.ByID(2432944859, repoId).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * GetBackupState gets backup state for given backup ID
 */
export function GetBackupState(backupId: types$0.BackupId): $CancellablePromise<statemachine$0.Backup | null> {
    return $Call.ByID(2620182497, backupId).then(($result: any) => {
        return $$createType13($result);
    });
}

/**
 * GetCombinedBackupProgress gets backup progress for given backup IDs
 */
export function GetCombinedBackupProgress(backupIds: types$0.BackupId[]): $CancellablePromise<types$1.BackupProgress | null> {
    return $Call.ByID(3581877548, backupIds).then(($result: any) => {
        return $$createType15($result);
    });
}

/**
 * GetConnectedRemoteHosts gets connected remote hosts
 */
export function GetConnectedRemoteHosts(): $CancellablePromise<string[]> {
    return $Call.ByID(423138286).then(($result: any) => {
        return $$createType16($result);
    });
}

/**
 * GetFilteredArchiveIds retrieves all archive IDs matching the filter criteria (without pagination)
 * This is used for "select all across pages" functionality
 */
export function GetFilteredArchiveIds(req: $models.PaginatedArchivesRequest | null): $CancellablePromise<number[]> {
    return $Call.ByID(2154529177, req).then(($result: any) => {
        return $$createType17($result);
    });
}

/**
 * GetLastArchiveByBackupId gets last archive for backup profile
 */
export function GetLastArchiveByBackupId(backupId: types$0.BackupId): $CancellablePromise<ent$0.Archive | null> {
    return $Call.ByID(2844713878, backupId).then(($result: any) => {
        return $$createType19($result);
    });
}

/**
 * GetLastArchiveByRepoId gets last archive for repository
 */
export function GetLastArchiveByRepoId(repoId: number): $CancellablePromise<ent$0.Archive | null> {
    return $Call.ByID(3556071828, repoId).then(($result: any) => {
        return $$createType19($result);
    });
}

/**
 * GetLastBackupErrorMsgByBackupId gets last backup error message for backup profile
 */
export function GetLastBackupErrorMsgByBackupId(bId: types$0.BackupId): $CancellablePromise<string> {
    return $Call.ByID(4136556109, bId);
}

export function GetLastBackupWarningByBackupId(bId: types$0.BackupId): $CancellablePromise<string> {
    return $Call.ByID(1506815150, bId);
}

/**
 * GetPaginatedArchives retrieves paginated archives for a repository
 */
export function GetPaginatedArchives(req: $models.PaginatedArchivesRequest | null): $CancellablePromise<$models.PaginatedArchivesResponse | null> {
    return $Call.ByID(3644900762, req).then(($result: any) => {
        return $$createType21($result);
    });
}

/**
 * GetPruningDates retrieves pruning dates for specified archives
 */
export function GetPruningDates(archiveIds: number[]): $CancellablePromise<$models.PruningDates> {
    return $Call.ByID(2102076250, archiveIds).then(($result: any) => {
        return $$createType22($result);
    });
}

/**
 * GetQueuedOperations returns all operations for a repository, optionally filtered by operation type
 */
export function GetQueuedOperations(repoId: number, operationType: statemachine$0.OperationType | null): $CancellablePromise<($models.SerializableQueuedOperation | null)[]> {
    return $Call.ByID(1376269121, repoId, operationType).then(($result: any) => {
        return $$createType23($result);
    });
}

/**
 * GetWithQueue retrieves a repository with queue information
 */
export function GetWithQueue(repoId: number): $CancellablePromise<$models.RepositoryWithQueue | null> {
    return $Call.ByID(144266353, repoId).then(($result: any) => {
        return $$createType25($result);
    });
}

/**
 * IsBorgRepository checks if a path contains a borg repository
 */
export function IsBorgRepository(path: string): $CancellablePromise<boolean> {
    return $Call.ByID(101129870, path);
}

/**
 * Mount mounts a repository
 */
export function Mount(repoId: number): $CancellablePromise<string> {
    return $Call.ByID(967190463, repoId);
}

/**
 * MountArchive mounts a specific archive
 */
export function MountArchive(archiveId: number): $CancellablePromise<string> {
    return $Call.ByID(1226599023, archiveId);
}

/**
 * QueueArchiveComment queues an archive comment update operation
 */
export function QueueArchiveComment(archiveId: number, comment: string): $CancellablePromise<string> {
    return $Call.ByID(3108311810, archiveId, comment);
}

/**
 * QueueArchiveDelete queues an archive deletion operation
 */
export function QueueArchiveDelete(archiveId: number): $CancellablePromise<string> {
    return $Call.ByID(3548195286, archiveId);
}

/**
 * QueueArchiveRename queues an archive rename operation
 */
export function QueueArchiveRename(archiveId: number, name: string): $CancellablePromise<string> {
    return $Call.ByID(4267028159, archiveId, name);
}

/**
 * QueueBackup queues a backup operation
 */
export function QueueBackup(backupId: types$0.BackupId): $CancellablePromise<string> {
    return $Call.ByID(875725915, backupId);
}

/**
 * QueueBackups queues multiple backup operations (convenience method)
 */
export function QueueBackups(backupIds: types$0.BackupId[]): $CancellablePromise<string[]> {
    return $Call.ByID(1401293560, backupIds).then(($result: any) => {
        return $$createType16($result);
    });
}

/**
 * QueueCheck queues a repository integrity check operation
 */
export function QueueCheck(repoId: number, quickVerification: boolean): $CancellablePromise<string> {
    return $Call.ByID(4176731931, repoId, quickVerification);
}

/**
 * QueuePrune queues a prune operation
 */
export function QueuePrune(backupId: types$0.BackupId): $CancellablePromise<string> {
    return $Call.ByID(295202139, backupId);
}

/**
 * RefreshArchives refreshes all archives of a repository
 */
export function RefreshArchives(repoId: number): $CancellablePromise<string> {
    return $Call.ByID(812894242, repoId);
}

/**
 * RegenerateSSHKey regenerates SSH key for ArcoCloud repositories
 */
export function RegenerateSSHKey(): $CancellablePromise<void> {
    return $Call.ByID(3683576253);
}

/**
 * Remove removes a repository from database only (does not delete physical repo)
 */
export function Remove(id: number): $CancellablePromise<void> {
    return $Call.ByID(2560302714, id);
}

/**
 * TestPathConnection tests if a path can connect to a valid borg repository.
 * Requires repository to be in Idle state (for borg call).
 * Returns:
 * - IsValid=false + ErrorMessage: Not idle (blocking)
 * - IsValid=true + ConnectionWarning: Connection failed (can proceed with warning)
 * - IsValid=true: Connection successful
 */
export function TestPathConnection(repoId: number, newPath: string, password: string): $CancellablePromise<$models.ValidatePathChangeResult | null> {
    return $Call.ByID(971940321, repoId, newPath, password).then(($result: any) => {
        return $$createType27($result);
    });
}

/**
 * TestRepoConnection tests connection to a repository
 */
export function TestRepoConnection(path: string, password: string): $CancellablePromise<$models.TestRepoConnectionResult> {
    return $Call.ByID(1151269054, path, password).then(($result: any) => {
        return $$createType28($result);
    });
}

/**
 * Unmount unmounts a repository
 */
export function Unmount(repoId: number): $CancellablePromise<string> {
    return $Call.ByID(3507624802, repoId);
}

/**
 * UnmountAllForRepos unmounts all mounts for specified repositories
 */
export function UnmountAllForRepos(repoIds: number[]): $CancellablePromise<any[]> {
    return $Call.ByID(1105783937, repoIds).then(($result: any) => {
        return $$createType29($result);
    });
}

/**
 * UnmountArchive unmounts a specific archive
 */
export function UnmountArchive(archiveId: number): $CancellablePromise<string> {
    return $Call.ByID(2999465112, archiveId);
}

/**
 * Update updates a repository with provided changes
 */
export function Update(repoId: number, updateReq: $models.UpdateRequest | null): $CancellablePromise<$models.Repository | null> {
    return $Call.ByID(3450666087, repoId, updateReq).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ValidateArchiveName validates an archive name
 */
export function ValidateArchiveName(archiveId: number, name: string): $CancellablePromise<string> {
    return $Call.ByID(392924285, archiveId, name);
}

/**
 * ValidatePathChange validates path format and uniqueness (no connection test).
 * Returns:
 * - IsValid=false + ErrorMessage: Blocking errors (cannot proceed)
 * - IsValid=true: Path is valid (connection not tested)
 */
export function ValidatePathChange(repoId: number, newPath: string): $CancellablePromise<$models.ValidatePathChangeResult | null> {
    return $Call.ByID(2418041363, repoId, newPath).then(($result: any) => {
        return $$createType27($result);
    });
}

/**
 * ValidateRepoName validates a repository name
 */
export function ValidateRepoName(name: string): $CancellablePromise<string> {
    return $Call.ByID(3060066791, name);
}

/**
 * ValidateRepoPath validates a repository path
 */
export function ValidateRepoPath(path: string, isLocal: boolean): $CancellablePromise<string> {
    return $Call.ByID(2882211019, path, isLocal);
}

// Private type creation functions
const $$createType0 = $models.Repository.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $models.ChangePassphraseResult.createFrom;
const $$createType4 = $models.ExaminePruningResult.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $models.FixStoredPasswordResult.createFrom;
const $$createType7 = $models.SerializableQueuedOperation.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = ent$0.BackupProfile.createFrom;
const $$createType10 = $Create.Nullable($$createType9);
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = statemachine$0.Backup.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
const $$createType14 = types$1.BackupProgress.createFrom;
const $$createType15 = $Create.Nullable($$createType14);
const $$createType16 = $Create.Array($Create.Any);
const $$createType17 = $Create.Array($Create.Any);
const $$createType18 = ent$0.Archive.createFrom;
const $$createType19 = $Create.Nullable($$createType18);
const $$createType20 = $models.PaginatedArchivesResponse.createFrom;
const $$createType21 = $Create.Nullable($$createType20);
const $$createType22 = $models.PruningDates.createFrom;
const $$createType23 = $Create.Array($$createType8);
const $$createType24 = $models.RepositoryWithQueue.createFrom;
const $$createType25 = $Create.Nullable($$createType24);
const $$createType26 = $models.ValidatePathChangeResult.createFrom;
const $$createType27 = $Create.Nullable($$createType26);
const $$createType28 = $models.TestRepoConnectionResult.createFrom;
const $$createType29 = $Create.Array($Create.Any);
