// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service contains the business logic and provides methods exposed to the frontend
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as arcov1$0 from "../../api/v1/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as state$0 from "../state/models.js";

/**
 * CancelSubscription cancels the user's subscription
 */
export function CancelSubscription(subscriptionID: string): $CancellablePromise<arcov1$0.CancelSubscriptionResponse | null> {
    return $Call.ByID(2256032254, subscriptionID).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ClearCheckoutResult clears the current checkout result
 */
export function ClearCheckoutResult(): $CancellablePromise<void> {
    return $Call.ByID(1431767263);
}

/**
 * CreateCheckoutSession creates a payment checkout session
 */
export function CreateCheckoutSession(planId: string): $CancellablePromise<arcov1$0.CreateCheckoutSessionResponse | null> {
    return $Call.ByID(54709411, planId).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * CreateCustomerPortalSession creates a pre-authenticated session URL for the Polar customer portal
 */
export function CreateCustomerPortalSession(): $CancellablePromise<arcov1$0.CreateCustomerPortalSessionResponse | null> {
    return $Call.ByID(1820936521).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * DowngradeSubscription schedules a plan downgrade for end of billing period
 */
export function DowngradeSubscription(subscriptionID: string, planID: string): $CancellablePromise<arcov1$0.DowngradeSubscriptionResponse | null> {
    return $Call.ByID(4264812557, subscriptionID, planID).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * GetCheckoutResult returns the current checkout result
 */
export function GetCheckoutResult(): $CancellablePromise<state$0.CheckoutResult | null> {
    return $Call.ByID(3825337690).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * GetCheckoutSession returns the current checkout session
 */
export function GetCheckoutSession(): $CancellablePromise<arcov1$0.CreateCheckoutSessionResponse | null> {
    return $Call.ByID(3805689501).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetSubscription returns the user's current subscription
 */
export function GetSubscription(): $CancellablePromise<arcov1$0.GetSubscriptionResponse | null> {
    return $Call.ByID(3325132602).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * ReactivateSubscription reactivates a cancelled subscription
 */
export function ReactivateSubscription(subscriptionID: string): $CancellablePromise<arcov1$0.ReactivateSubscriptionResponse | null> {
    return $Call.ByID(1542251936, subscriptionID).then(($result: any) => {
        return $$createType13($result);
    });
}

/**
 * UpgradeSubscription performs immediate plan upgrade with proration
 */
export function UpgradeSubscription(subscriptionID: string, planID: string): $CancellablePromise<arcov1$0.UpgradeSubscriptionResponse | null> {
    return $Call.ByID(3859866138, subscriptionID, planID).then(($result: any) => {
        return $$createType15($result);
    });
}

// Private type creation functions
const $$createType0 = arcov1$0.CancelSubscriptionResponse.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = arcov1$0.CreateCheckoutSessionResponse.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = arcov1$0.CreateCustomerPortalSessionResponse.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = arcov1$0.DowngradeSubscriptionResponse.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = state$0.CheckoutResult.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = arcov1$0.GetSubscriptionResponse.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = arcov1$0.ReactivateSubscriptionResponse.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
const $$createType14 = arcov1$0.UpgradeSubscriptionResponse.createFrom;
const $$createType15 = $Create.Nullable($$createType14);
